plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/yikwong/Documents/GitHub/Rivex_pitchdesk_mar26"
publishOrigin = "config"

[build.environment]

[build.processing]
skip_processing = true

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]